[imp] add checkpoint straight from backend record
OCA/connector pull request #220
Opened 2016-10-25 14:50 UTC by simahawk

Goal: simply the checkpoint story.

**Now**

ATM you have to define this in your own code
```
from openerp.addons.connector.checkpoint import checkpoint

def add_checkpoint(session, model_name, record_id, backend_id, message=''):
    """Add checkpoint for prestashop backend."""
    return checkpoint.add_checkpoint(session, model_name, record_id,
                                     'prestashop.backend', backend_id)

def add_checkpoint_message(session, backend_id, message=''):
    """Add checkpoint message for prestashop backend."""
    return checkpoint.add_checkpoint_message(
        session, 'prestashop.backend', backend_id, message=message)
```
and then you have to import those functions, etc.

The point is: you always need your backend record to add a checkpoint.

**Improvement**

You just do this
```
backend_record.add_checkpoint(
        model='res.partner', record_id=1, message='VAT number can be missing')
```
or
```
backend_record.add_checkpoint(message='Failed import for category Foo')
```

Tests updated.

2016-10-25 15:08 UTC, lmignon requested changes

2016-10-25 15:08 UTC, lmignon commented on connector/backend_model.py
> +    @api.model
`@api.mult`i otherwise `self.id` can be empty

2016-10-25 15:21 UTC, simahawk commented on connector/backend_model.py
> +    @api.model
typo fixed, thanks! :)

2016-10-25 15:48 UTC, lmignon commented on connector/backend_model.py
> +    def add_checkpoint(self, model=None, record_id=None, message=''):
Why a default empty string for param `message`?

2016-10-25 16:04 UTC, lasley commented on connector/checkpoint/checkpoint.py
> +# TODO: deprecate these since we can now add checkpoints
It would be nice if there were a `_logger.warn(` to indicate the deprecation log-side

2016-10-25 16:05 UTC, lasley requested changes
Lint is 🔴

2016-10-26 07:03 UTC, simahawk commented
@lasley the build is red for docs lint, in OCA repo too https://travis-ci.org/OCA/connector/jobs/170488884
I'll check the reason but I didn't touch all those file, just 2 of them, so I wonder if there's an issue on Travis with such tests.

2016-10-26 07:13 UTC, simahawk commented on connector/backend_model.py
> +    def add_checkpoint(self, model=None, record_id=None, message=''):
@lmignon updated

2016-10-26 07:13 UTC, simahawk commented on connector/checkpoint/checkpoint.py
> +# TODO: deprecate these since we can now add checkpoints
@lasley done

2016-10-26 07:17 UTC, lmignon approved these changes

2016-10-26 07:18 UTC, lmignon commented
@simahawk Thank you for these improvements!

2016-10-26 08:33 UTC, simahawk commented
@lasley oops, I left behind an import... fixed and build is green again ;)

2016-10-26 16:16 UTC, lasley approved these changes
Thanks @simahawk

2016-11-03 07:46 UTC, guewen approved these changes

2016-11-03 07:46 UTC, merged