[8.0] add new module to manage job subscription
OCA/connector pull request #227
Opened 2016-12-07 10:51 UTC by Cedric-Pigeon

Sometimes, user must manage jobs and must be Connector manager but they don't want to receive mails or notifications.
This new module adds a flag on user form to let him the choice of receiving notifications or not.

2016-12-08 06:35 UTC, guewen commented on connector_job_subscribe/models/res_users.py
> +                                   default=True)
Could you add a tooltip explaining that job notifications are sent only when this is active AND the user is a connector manager?

2016-12-08 08:25 UTC, Cedric-Pigeon commented on connector_job_subscribe/models/res_users.py
> +                                   default=True)
@guewen Done, thanks.

2016-12-08 08:26 UTC, lmignon commented on connector_job_subscribe/models/res_users.py
> +                                   default=True)
@Cedric-Pigeon Could you add an index on this new field since it's used the subscribe domain? This index will be only useful for large installation with a lot of users therefore it's a Nice to Have :smirk:

2016-12-08 08:34 UTC, Cedric-Pigeon commented on connector_job_subscribe/models/res_users.py
> +                                   default=True)
@lmignon Done, thanks.

2016-12-20 08:43 UTC, Cedric-Pigeon commented
@guewen @lmignon Is it ok for you now ? Thanks.

2016-12-22 13:55 UTC, guewen commented
Thanks! Still a few pep8 issues to fix and we're ready to merge.
I fixed the ones in the `connector` module here: https://github.com/OCA/connector/pull/228

2017-02-15 06:37 UTC, Cedric-Pigeon commented
@guewen flake8 fixed, all checks are green

2017-02-15 08:16 UTC, lmignon approved these changes
LGTM Code review

2017-02-15 18:37 UTC, sebalix requested changes
Nice module, code review (just a typo, I think?)

2017-02-15 18:37 UTC, sebalix commented on connector_job_subscribe/views/res_users_view.xml
> +        <record id="view_puser_connector_form" model="ir.ui.view">
`puser`, maybe a typo?

2017-02-20 21:43 UTC, Cedric-Pigeon commented
@sebalix Typo fixed

2017-02-21 07:33 UTC, sebalix approved these changes
:+1:

2017-04-04 15:22 UTC, merged