MIGR 14. component_event
OCA/connector pull request #384
Opened 2020-10-12 19:39 UTC by bealdav

2020-10-16 12:23 UTC, eantones commented
@bealdav  I created a PR https://github.com/akretion/connector/pull/2 on your branch fixing some migration issues. Please review it. Thanks

2020-10-21 08:29 UTC, eantones requested changes

2020-10-21 08:29 UTC, eantones commented on test-requirements.txt
> +odoo14-addon-component_event @ git+https://github.com/OCA/connector@refs/pull/382/head#subdirectory=setup/connector_event
@bealdav Shouldn't be pointing at **component** instead of **component_event** (itself)? Also I think that the subdirectory **setup/connector_event** should be **setup/component**. In summary, I think it should be:

`odoo14-addon-component @ git+https://github.com/OCA/connector@refs/pull/382/head#subdirectory=setup/component`

2020-10-22 12:52 UTC, eantones approved these changes

2020-10-26 14:11 UTC, guewen commented on test-requirements.txt
> +odoo14-addon-component_event @ git+https://github.com/OCA/connector@refs/pull/382/head#subdirectory=setup/connector_event
component is now merged

2020-10-26 14:29 UTC, bealdav commented on test-requirements.txt
> +odoo14-addon-component_event @ git+https://github.com/OCA/connector@refs/pull/382/head#subdirectory=setup/connector_event
I removed content here @guewen

2020-10-26 15:31 UTC, guewen approved these changes

2020-10-26 15:31 UTC, guewen commented
/ocabot merge nobump

2020-10-26 16:20 UTC, merged