[14.0][MIG] connector_base_product
OCA/connector pull request #405
Opened 2021-05-16 10:03 UTC by hailangvn

2021-05-16 10:42 UTC, MeetKD requested changes
Minor change.

2021-05-16 10:42 UTC, MeetKD commented on connector_base_product/views/product_view.xml
> +
Can you please remove the extra spaces?

2021-05-31 08:26 UTC, leemannd approved these changes

2021-06-05 08:39 UTC, guewen approved these changes

2021-06-05 08:39 UTC, guewen commented
/ocabot merge nobump

Thank you!

2021-06-05 09:11 UTC, merged